# ekf config file
ekf_filter_node:
  ros__parameters:
    frequency: 30.0
#if true, ignores small variations in ground plane and assume a 2d planar world
    two_d_mode: true
    publish_acceleration: true
# if true, publishes transformation over /tf topic
    publish_tf: true

# set the map, odom, base_link, and world frames 
# set world frame to odom because using position data with wheel encoders and IMU
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    odom0: /odometry
    odom0_config: [true, true, false,  # x, y, z
                  false, false, true,  # roll, pitch, yaw
                  true,  true,  false, # vx, vy, vz
                  false, false, true,  # vroll, vpitch, vyaw
                  false, false, false] # ax, ay, az, aroll, apitch, ayaw

    # imu0: /imu
    # imu0_config: [false, false, false,
    #               false, false, false,
    #               false, false, false,
    #               false, false, true,
    #               true, true, true]
